#!/usr/bin/env python3
"""Single hub regeneration command (Round-2 §8/§9 — the "one generator").

Run this after ANY hub-data change (new import, review, registry edit). It
rebuilds, in one shot:
  1. hub/canonical_results.json   <- hub/imports/ (+ quarantined hub/legacy/)
  2. README results section       <- canonical (omnidocbench_rocm.registry generate)
  3. README comparison table      <- registry.yaml + canonical (generate_registry.py)

CI gates (quality/contracts, required on main post-P0) verify freshness, so a
forgotten regeneration is caught before merge — but this command means there is
only ONE thing to remember, not three.
"""
from __future__ import annotations
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "engine"))
from omnidocbench_rocm import hub  # noqa: E402


def _run(args):
    return subprocess.run([sys.executable, *args], cwd=REPO, capture_output=True, text=True)


def main() -> int:
    # 1. canonical <- imports + legacy
    doc = hub.rebuild_canonical(REPO / "hub")
    (REPO / "hub" / "canonical_results.json").write_text(
        json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"[regen] canonical rebuilt: {len(doc['results'])} rows "
          f"({sum(1 for r in doc['results'] if r.get('status') == 'valid')} valid)")

    # 2. README results section <- canonical
    r = _run(["-m", "omnidocbench_rocm.registry", "generate"])
    print("[regen] results section:", (r.stdout or r.stderr).strip().splitlines()[-1] if (r.stdout or r.stderr) else "(no output)")

    # 3. README comparison table <- generate_registry.py, spliced into the block
    out = _run(["scripts/generate_registry.py", "hub/registry.yaml"]).stdout.rstrip("\n")
    readme = (REPO / "README.md").read_text(encoding="utf-8")
    s = readme.index("<!-- registry-table -->")
    e = readme.index("<!-- /registry-table -->") + len("<!-- /registry-table -->")
    block = ("<!-- registry-table -->\n"
             "<!-- generated by scripts/generate_registry.py -- do not edit manually -->\n\n"
             + out + "\n<!-- /registry-table -->")
    (REPO / "README.md").write_text(readme[:s] + block + readme[e:], encoding="utf-8")
    print("[regen] comparison table spliced")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
